import { ImageResponse } from "next/og";
import { readFile } from "node:fs/promises";
import { join } from "node:path";

export const alt = "Moodflix Home - AI Movie Discovery";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default async function Image() {
  // Load pre-blurred movie poster collage (generated by scripts/generate-og-base.js)
  const bgData = await readFile(join(process.cwd(), "public/og-base.png"));
  const bgSrc = `data:image/png;base64,${bgData.toString("base64")}`;

  // Load Bebas Neue font for Satori (cannot use next/font/google CSS variables here)
  // Must use woff format — Satori does not support woff2
  const fontData = await readFile(
    join(process.cwd(), "assets/BebasNeue-Regular.woff")
  );

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          backgroundColor: "#0a0a0a",
          position: "relative",
        }}
      >
        {/* Pre-blurred movie poster collage background */}
        {/* eslint-disable-next-line jsx-a11y/alt-text -- decorative background in Satori OG context */}
        <img
          src={bgSrc}
          style={{
            position: "absolute",
            top: 0,
            left: 0,
            width: "100%",
            height: "100%",
            objectFit: "cover",
            opacity: 0.5,
          }}
        />

        {/* Dark vignette gradient overlay */}
        <div
          style={{
            position: "absolute",
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            background:
              "linear-gradient(135deg, rgba(10,10,10,0.90) 0%, rgba(10,10,10,0.65) 50%, rgba(10,10,10,0.90) 100%)",
            display: "flex",
          }}
        />

        {/* Centered wordmark — LOGO ONLY, no subtitle (locked user decision) */}
        <div
          style={{
            position: "relative",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          {/* MOODFLIX — crimson M + white OODFLIX */}
          <div
            style={{
              display: "flex",
              fontSize: 130,
              fontFamily: "BebasNeue",
              letterSpacing: "-3px",
              lineHeight: 1,
            }}
          >
            <span style={{ color: "#FB2C36" }}>M</span>
            <span style={{ color: "#ffffff" }}>OODFLIX</span>
          </div>

          {/* Thin crimson rule below wordmark */}
          <div
            style={{
              width: 80,
              height: 3,
              backgroundColor: "#FB2C36",
              marginTop: 16,
              display: "flex",
            }}
          />
        </div>
      </div>
    ),
    {
      ...size,
      fonts: [
        {
          name: "BebasNeue",
          data: fontData,
          style: "normal",
          weight: 400,
        },
      ],
    }
  );
}
